### ISSUE TITLE
Update to C#6

### ISSUE THREAD

**Issue by NikitaEgorov** [schlotter/Community.StyleCop.Rules#2]
I try to use community rules with Visual-StyleCop (https://github.com/ptittof57/Visual-StyleCop) and get incorrect errors with end line whitespaces

**Comment by ptittof57** [comment]
@NikitaEgorov, @schlotter It seems that current project must be updated to target framework 4.6 to build with Visual-StyleCop dlls in first step. No problem for me to help you and @schlotter if he is ok but could you provide an exemple of file where you get incorrect errors with end line whitespaces ?

**Comment by NikitaEgorov** [comment]
I had troubles with Expression bodies
public string Name => First + " " + Last;

**Comment by schlotter** [comment]
Thanks for your comments. Which should be the StyleCop version we refer to?

[StyleCop](https://www.nuget.org/packages/StyleCop/) does not seem to be actively developed, while [Visual StyleCop](https://www.nuget.org/packages/Visual-StyleCop.MSBuild/) seems to be.

It's probably a bit old-fashioned that we still ship the DLLs with this solution. Instead, we should refer the corresponding NuGet package. :-)

**Comment by praveennet** [comment]
https://www.nuget.org/packages/StyleCop.MSBuild seems to be active. Is it possible to add Community Rules as part of StyleCop.MSBuild itself? or create a separate NuGet package which can work well with StyleCop.MsBuild package?

**Comment by schlotter** [comment]
Both suggestions are possible. I guess it just takes someone to do it. I will definitely accept pull requests.

**Comment by schlotter** [comment]
This repo will be archived soon as it became incompatible with StyleCop.Analyzers.
